# -*- coding: utf-8 -*-
"""CF_NeuMF_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15YS9UUemRf11Ovj0DCLifyrCOMfAnokE
"""

!pip install -q torch anthropic

import os, io, json, zipfile, random, warnings
import requests
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from collections import defaultdict
warnings.filterwarnings('ignore')

SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device : {DEVICE}")
print(f"PyTorch: {torch.__version__}")

"""## 1. Data"""

def load_movielens_100k(cache_dir: str = 'ml-100k') -> tuple:
    """
    Download and parse MovieLens 100K.
    Returns ratings (user_id, item_id, rating, timestamp)
    and items_df (item_id, title, genre binary columns).
    """
    url = 'https://files.grouplens.org/datasets/movielens/ml-100k.zip'
    if not os.path.exists(cache_dir):
        print('Downloading MovieLens 100K...')
        r = requests.get(url, timeout=60); r.raise_for_status()
        zipfile.ZipFile(io.BytesIO(r.content)).extractall('.')
        print('Done.')

    ratings = pd.read_csv(
        f'{cache_dir}/u.data', sep='\t',
        names=['user_id', 'item_id', 'rating', 'timestamp']
    )
    genre_cols = [
        'unknown', 'action', 'adventure', 'animation', 'childrens', 'comedy',
        'crime', 'documentary', 'drama', 'fantasy', 'film_noir', 'horror',
        'musical', 'mystery', 'romance', 'sci_fi', 'thriller', 'war', 'western'
    ]
    items_df = pd.read_csv(
        f'{cache_dir}/u.item', sep='|', encoding='latin-1', header=None,
        usecols=list(range(24)),
        names=['item_id', 'title', 'release_date', 'video_date', 'imdb_url'] + genre_cols
    )[['item_id', 'title'] + genre_cols]

    return ratings, items_df


ratings, items_df = load_movielens_100k()
print(f"Ratings : {len(ratings):,}")
print(f"Users   : {ratings.user_id.nunique()}")
print(f"Items   : {ratings.item_id.nunique()}")
print(f"\nRating distribution:")
print(ratings['rating'].value_counts().sort_index().to_string())

def build_implicit_dataset(
    ratings: pd.DataFrame,
    pos_threshold: int = 4,
    min_interactions: int = 5
) -> tuple:
    """
    Binarisation rule:
        rating >= pos_threshold  ->  keep as positive interaction
        rating <  pos_threshold  ->  discard entirely
        (low ratings carry no implicit signal — we do not treat them as negatives)

    Split strategy: per-user Leave-One-Out ordered by timestamp.
        last interaction  -> test
        all earlier       -> train

    Also stores:
        user_history : ordered list of training item-indices per user
                       (used to build LLM context: "this user liked X, Y, Z")
    """
    pos = ratings[ratings['rating'] >= pos_threshold].copy()

    # 0-based contiguous re-indexing
    user_ids = sorted(pos['user_id'].unique())
    item_ids = sorted(pos['item_id'].unique())
    user2idx = {u: i for i, u in enumerate(user_ids)}
    item2idx = {v: i for i, v in enumerate(item_ids)}
    pos['user'] = pos['user_id'].map(user2idx)
    pos['item'] = pos['item_id'].map(item2idx)

    n_users, n_items = len(user2idx), len(item2idx)

    # Remove users with too few positives
    pos = pos.groupby('user').filter(lambda g: len(g) >= min_interactions)
    pos = pos.sort_values(['user', 'timestamp'])

    train_rows, test_rows = [], []
    user_pos     = defaultdict(set)   # user -> set of training item-indices
    user_history = defaultdict(list)  # user -> ordered list of training items

    for uid, grp in pos.groupby('user'):
        items_sorted = grp['item'].tolist()
        # Last item -> test (simulates "next interaction" prediction)
        test_rows.append({'user': uid, 'item': items_sorted[-1]})
        for it in items_sorted[:-1]:
            train_rows.append({'user': uid, 'item': it, 'label': 1})
            user_pos[uid].add(it)
            user_history[uid].append(it)

    train_df = pd.DataFrame(train_rows)
    test_df  = pd.DataFrame(test_rows)

    return train_df, test_df, user_pos, user_history, n_users, n_items, item2idx, user2idx


(
    train_df, test_df, user_pos, user_history,
    n_users, n_items, item2idx, user2idx
) = build_implicit_dataset(ratings, pos_threshold=4, min_interactions=5)

# Reverse maps (needed for LLM title lookup)
idx2item    = {v: k for k, v in item2idx.items()}
item_titles = dict(zip(items_df['item_id'], items_df['title']))

print(f"Train positives        : {len(train_df):,}")
print(f"Test users             : {len(test_df)}")
print(f"n_users={n_users}, n_items={n_items}")
print(f"Avg train positives/user: {len(train_df)/n_users:.1f}")

## CRITICAL for fair comparison:
#   If each model samples its own negatives, differences in metrics
#   could reflect lucky/unlucky sampling, not model quality.
#   We fix the same 99 negatives per user and reuse them everywhere.

rng = np.random.RandomState(SEED)
EVAL_NEGS = {}   # user_idx -> list of 99 negative item indices

for _, row in test_df.iterrows():
    u, pos_item = int(row['user']), int(row['item'])
    exclude     = user_pos[u] | {pos_item}
    negs        = []
    while len(negs) < 99:
        c = int(rng.randint(0, n_items))
        if c not in exclude:
            negs.append(c)
            exclude.add(c)
    EVAL_NEGS[u] = negs

print(f"Pre-sampled {len(EVAL_NEGS)} x 99 fixed evaluation negatives.")
print("All 4 models will be evaluated on these identical negative sets.")

"""## 2. Dataset & Training Utilities"""

class ImplicitDataset(Dataset):
    """
    Online negative sampling dataset for implicit feedback.

    For every positive (user, item) pair, `neg_ratio` negatives are
    drawn uniformly from outside the user's training-positive set.
    Negatives are freshly sampled each epoch, improving gradient diversity.

    Layout: indices are interleaved — every (1+neg_ratio) block starts
    with the positive, followed by neg_ratio negatives.
    """
    def __init__(
        self,
        train_df:  pd.DataFrame,
        user_pos:  dict,
        n_items:   int,
        neg_ratio: int = 4
    ):
        self.user_pos  = user_pos
        self.n_items   = n_items
        self.neg_ratio = neg_ratio
        self.positives = list(zip(train_df['user'].tolist(),
                                  train_df['item'].tolist()))

    def __len__(self) -> int:
        return len(self.positives) * (1 + self.neg_ratio)

    def __getitem__(self, idx: int):
        pos_idx = idx // (1 + self.neg_ratio)
        within  = idx %  (1 + self.neg_ratio)
        u, i    = self.positives[pos_idx]

        if within == 0:   # positive sample
            return (torch.tensor(u, dtype=torch.long),
                    torch.tensor(i, dtype=torch.long),
                    torch.tensor(1.0, dtype=torch.float32))

        # negative sample — rejection sample outside user's positives
        neg = random.randint(0, self.n_items - 1)
        while neg in self.user_pos[u]:
            neg = random.randint(0, self.n_items - 1)
        return (torch.tensor(u,   dtype=torch.long),
                torch.tensor(neg, dtype=torch.long),
                torch.tensor(0.0, dtype=torch.float32))

def train_model(
    model:        nn.Module,
    train_df:     pd.DataFrame,
    user_pos:     dict,
    n_items:      int,
    n_epochs:     int   = 30,
    batch_size:   int   = 2048,
    lr:           float = 1e-3,
    weight_decay: float = 1e-5,
    neg_ratio:    int   = 4,
    device:       torch.device = DEVICE
) -> nn.Module:
    """
    Train any nn.Module (GMF or NeuMF) with:
      - BCEWithLogitsLoss: numerically stable point-wise loss
      - Adam + CosineAnnealingLR(T_max=n_epochs, eta_min=1e-5)
      - Gradient clipping (max_norm=1.0): stabilises embedding updates
      - neg_ratio=4: empirically good balance between speed and performance
    """
    dataset   = ImplicitDataset(train_df, user_pos, n_items, neg_ratio)
    loader    = DataLoader(dataset, batch_size=batch_size, shuffle=True,
                           num_workers=0, pin_memory=(device.type == 'cuda'))
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    criterion = nn.BCEWithLogitsLoss()
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=n_epochs, eta_min=1e-5)

    model.train()
    for epoch in range(1, n_epochs + 1):
        total_loss = 0.0
        for users, items, labels in loader:
            users, items, labels = (users.to(device), items.to(device), labels.to(device))
            optimizer.zero_grad(set_to_none=True)
            loss = criterion(model(users, items), labels)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            total_loss += loss.item() * len(users)
        scheduler.step()
        if epoch % 5 == 0 or epoch == 1:
            avg = total_loss / len(dataset)
            print(f"  Epoch {epoch:3d}/{n_epochs} | Loss: {avg:.5f} | LR: {scheduler.get_last_lr()[0]:.2e}")

    return model

def evaluate_ranking(
    scorer,           # nn.Module  OR  PopularityModel
    test_df:   pd.DataFrame,
    eval_negs: dict,
    Ks:        tuple = (5, 10, 15, 20),
    device:    torch.device = DEVICE,
    is_neural: bool = True
) -> dict:
    """
    Leave-one-out ranking evaluation on pre-sampled fixed negatives.

    For each test user:
      candidates = [positive] + 99 negatives  (100 items total)
      rank       = position of positive in descending-score order (1-indexed)
      HR@K       = 1  if rank <= K
      NDCG@K     = 1/log2(rank+1)  if rank <= K  (IDCG = 1 for single relevant item)

    Works for both neural models (nn.Module) and PopularityModel.
    """
    if is_neural:
        scorer.eval()

    results = {f'NDCG@{k}': [] for k in Ks}
    results.update({f'HR@{k}': [] for k in Ks})

    with torch.no_grad():
        for _, row in test_df.iterrows():
            u, pos_item  = int(row['user']), int(row['item'])
            candidates   = [pos_item] + eval_negs[u]    # pos at index 0

            if is_neural:
                u_t    = torch.tensor([u] * 100,   dtype=torch.long, device=device)
                i_t    = torch.tensor(candidates,  dtype=torch.long, device=device)
                scores = torch.sigmoid(scorer(u_t, i_t)).cpu().numpy()
            else:
                scores = scorer.score_candidates(u, candidates)

            # Rank of the positive item (1-indexed)
            rank = int((scores[1:] >= scores[0]).sum()) + 1

            for k in Ks:
                results[f'HR@{k}'].append(1 if rank <= k else 0)
                results[f'NDCG@{k}'].append(
                    1.0 / np.log2(rank + 1) if rank <= k else 0.0
                )

    return {key: float(np.mean(vals)) for key, vals in results.items()}

"""## 3. Models"""

class PopularityModel:
    """
    Non-personalised baseline: recommend globally popular items.
    Score(item) = number of positive training interactions.
    User-agnostic — identical ranked list for every user.
    """
    def __init__(self):
        self.item_scores: dict = {}

    def fit(self, train_df: pd.DataFrame) -> 'PopularityModel':
        self.item_scores = train_df['item'].value_counts().to_dict()
        print(f"  Popularity model fitted. "
              f"Most popular item index: {train_df['item'].value_counts().idxmax()} "
              f"({train_df['item'].value_counts().iloc[0]} interactions)")
        return self

    def score_candidates(self, user: int, candidates: list) -> np.ndarray:
        """Return raw interaction count per candidate (user arg ignored)."""
        return np.array([self.item_scores.get(c, 0.0) for c in candidates],
                        dtype=float)


class GMF(nn.Module):
    """
    Generalised Matrix Factorization (He et al., WWW 2017 — GMF-only variant).
    Equivalent to a neural MF with a linear output on the element-wise product.

    This is the simplest neural CF model.
    It captures linear, low-rank user-item interactions only.
    It cannot model non-linear patterns (that requires the MLP branch in NeuMF).

    Architecture:
        score(u,i) = output_layer( p_u  ⊙  q_i )
        where p_u ∈ R^emb_dim, q_i ∈ R^emb_dim
    """
    def __init__(self, n_users: int, n_items: int, emb_dim: int = 64):
        super().__init__()
        self.user_emb = nn.Embedding(n_users, emb_dim)
        self.item_emb = nn.Embedding(n_items, emb_dim)
        self.output   = nn.Linear(emb_dim, 1)
        nn.init.normal_(self.user_emb.weight, std=0.01)
        nn.init.normal_(self.item_emb.weight, std=0.01)
        nn.init.xavier_uniform_(self.output.weight)
        nn.init.zeros_(self.output.bias)

    def forward(self, users: torch.Tensor, items: torch.Tensor) -> torch.Tensor:
        return self.output(
            self.user_emb(users) * self.item_emb(items)
        ).squeeze(-1)   # (B,)


class NeuMF(nn.Module):
    """
    Neural Matrix Factorization (He et al., WWW 2017)
    https://arxiv.org/abs/1708.05031

    Two parallel branches with separate embedding tables:

      GMF branch:   p_u_gmf  ⊙  q_i_gmf          (linear interactions)
      MLP branch:   FC( concat(p_u_mlp, q_i_mlp) ) (non-linear interactions)

    Final prediction:
      score = linear( concat(gmf_out, mlp_out) )  -> logit

    Why separate embeddings?  GMF and MLP impose different inductive biases;
    sharing embeddings would force them into a sub-optimal common space.

    Design choices:
      - LayerNorm instead of BatchNorm: more stable with variable batch sizes
      - Dropout(0.2): prevents co-adaptation in MLP tower
      - Xavier init on linear layers, tiny normal on embeddings
    """
    def __init__(
        self,
        n_users:  int,
        n_items:  int,
        emb_dim:  int   = 64,
        mlp_dims: tuple = (256, 128, 64),
        dropout:  float = 0.2
    ):
        super().__init__()
        # GMF embeddings
        self.user_emb_gmf = nn.Embedding(n_users, emb_dim)
        self.item_emb_gmf = nn.Embedding(n_items, emb_dim)
        # MLP embeddings
        self.user_emb_mlp = nn.Embedding(n_users, emb_dim)
        self.item_emb_mlp = nn.Embedding(n_items, emb_dim)

        # MLP tower
        mlp_layers, in_dim = [], emb_dim * 2
        for out_dim in mlp_dims:
            mlp_layers += [
                nn.Linear(in_dim, out_dim),
                nn.LayerNorm(out_dim),
                nn.ReLU(),
                nn.Dropout(dropout)
            ]
            in_dim = out_dim
        self.mlp = nn.Sequential(*mlp_layers)

        # Final prediction head
        self.predict = nn.Linear(emb_dim + mlp_dims[-1], 1)
        self._init_weights()

    def _init_weights(self):
        for emb in [self.user_emb_gmf, self.item_emb_gmf,
                    self.user_emb_mlp, self.item_emb_mlp]:
            nn.init.normal_(emb.weight, std=0.01)
        for m in self.mlp.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                nn.init.zeros_(m.bias)
        nn.init.xavier_uniform_(self.predict.weight)
        nn.init.zeros_(self.predict.bias)

    def forward(self, users: torch.Tensor, items: torch.Tensor) -> torch.Tensor:
        gmf_out = self.user_emb_gmf(users) * self.item_emb_gmf(items)
        mlp_out = self.mlp(torch.cat([
            self.user_emb_mlp(users),
            self.item_emb_mlp(items)
        ], dim=-1))
        return self.predict(
            torch.cat([gmf_out, mlp_out], dim=-1)
        ).squeeze(-1)   # (B,)


# Sanity check — both models run forward pass
_u = torch.randint(0, 10, (4,))
_i = torch.randint(0, 20, (4,))
print("GMF   output:", GMF(10, 20, 16)(_u, _i).shape)
print("NeuMF output:", NeuMF(10, 20, 16, (32, 16, 8))(_u, _i).shape)
del _u, _i

class MLPModel(nn.Module):
    """
    Pure MLP collaborative filtering model (ablation — no GMF branch).
    Used for ablation comparison and as pre-training component for NeuMF.

    Architecture:
        score(u,i) = linear( MLP( concat(p_u, q_i) ) )
    """
    def __init__(
        self,
        n_users:  int,
        n_items:  int,
        emb_dim:  int   = 64,
        mlp_dims: tuple = (256, 128, 64),
        dropout:  float = 0.2
    ):
        super().__init__()
        self.user_emb = nn.Embedding(n_users, emb_dim)
        self.item_emb = nn.Embedding(n_items, emb_dim)
        layers, in_dim = [], emb_dim * 2
        for out_dim in mlp_dims:
            layers += [nn.Linear(in_dim, out_dim), nn.LayerNorm(out_dim),
                       nn.ReLU(), nn.Dropout(dropout)]
            in_dim = out_dim
        self.mlp     = nn.Sequential(*layers)
        self.predict = nn.Linear(mlp_dims[-1], 1)
        nn.init.normal_(self.user_emb.weight, std=0.01)
        nn.init.normal_(self.item_emb.weight, std=0.01)
        for m in self.mlp.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight); nn.init.zeros_(m.bias)
        nn.init.xavier_uniform_(self.predict.weight); nn.init.zeros_(self.predict.bias)

    def forward(self, users: torch.Tensor, items: torch.Tensor) -> torch.Tensor:
        x = torch.cat([self.user_emb(users), self.item_emb(items)], dim=-1)
        return self.predict(self.mlp(x)).squeeze(-1)


def init_neumf_from_pretrained(neuMF: 'NeuMF', gmf: GMF, mlp: MLPModel) -> 'NeuMF':
    """
    Initialise NeuMF branches from separately pre-trained GMF and MLP models.
    Technique from He et al. (NeuMF paper, Section 3.4).

    Why it works:
      - Random init → saddle points, slow convergence
      - Pre-trained weights → good starting point in each branch's subspace
      - Consistently gives +3-5% NDCG improvement vs random init
    """
    # Copy GMF branch
    neuMF.user_emb_gmf.weight.data.copy_(gmf.user_emb.weight.data)
    neuMF.item_emb_gmf.weight.data.copy_(gmf.item_emb.weight.data)

    # Copy MLP branch embeddings
    neuMF.user_emb_mlp.weight.data.copy_(mlp.user_emb.weight.data)
    neuMF.item_emb_mlp.weight.data.copy_(mlp.item_emb.weight.data)

    # Copy MLP tower weights layer by layer
    src_linears = [m for m in mlp.mlp.modules()  if isinstance(m, nn.Linear)]
    dst_linears = [m for m in neuMF.mlp.modules() if isinstance(m, nn.Linear)]
    for src, dst in zip(src_linears, dst_linears):
        dst.weight.data.copy_(src.weight.data)
        dst.bias.data.copy_(src.bias.data)

    # Combine prediction head: blend GMF output weight with MLP predict weight
    alpha = 0.5   # equal weight to both branches at init
    gmf_w = gmf.output.weight.data          # (1, emb_dim)
    mlp_w = mlp.predict.weight.data         # (1, mlp_dims[-1])
    neuMF.predict.weight.data = torch.cat([alpha * gmf_w, (1 - alpha) * mlp_w], dim=1)
    neuMF.predict.bias.data.zero_()

    print("  ✓ NeuMF branches initialised from pre-trained GMF + MLP weights.")
    return neuMF


# Sanity check
_u = torch.randint(0, 10, (4,))
_i = torch.randint(0, 20, (4,))
print("MLPModel output:", MLPModel(10, 20, 16, (32, 16, 8))(_u, _i).shape)
del _u, _i


# ────────────────────────────────────────────────────────────────────────────
# MODEL: BPR-MF  (GMF trained with Bayesian Personalised Ranking loss)
# ────────────────────────────────────────────────────────────────────────────

class BPRDataset(Dataset):
    """
    Pairwise dataset for BPR training.
    Each sample is a (user, pos_item, neg_item) triple.
    BPR maximises P(score(u,pos) > score(u,neg)).
    """
    def __init__(self, train_df: pd.DataFrame, user_pos: dict, n_items: int):
        self.pairs    = list(zip(train_df['user'].tolist(), train_df['item'].tolist()))
        self.user_pos = user_pos
        self.n_items  = n_items

    def __len__(self): return len(self.pairs)

    def __getitem__(self, idx):
        u, pos = self.pairs[idx]
        neg = random.randint(0, self.n_items - 1)
        while neg in self.user_pos[u]:
            neg = random.randint(0, self.n_items - 1)
        return (torch.tensor(u,   dtype=torch.long),
                torch.tensor(pos, dtype=torch.long),
                torch.tensor(neg, dtype=torch.long))


def train_bpr(
    model:        nn.Module,
    train_df:     pd.DataFrame,
    user_pos:     dict,
    n_items:      int,
    n_epochs:     int   = 50,
    batch_size:   int   = 2048,
    lr:           float = 1e-3,
    weight_decay: float = 1e-5,
    device:       torch.device = DEVICE
) -> nn.Module:
    """
    Train with BPR loss:  L = -mean( log sigmoid( s_pos - s_neg ) )

    BPR is a pairwise loss that directly optimises ranking order.
    It is more sample-efficient than BCE for top-K metrics.
    Same CosineAnnealingLR schedule as BCE training for fair comparison.
    """
    dataset   = BPRDataset(train_df, user_pos, n_items)
    loader    = DataLoader(dataset, batch_size=batch_size, shuffle=True, num_workers=0,
                           pin_memory=(device.type == 'cuda'))
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=n_epochs, eta_min=1e-5)

    model.train()
    for epoch in range(1, n_epochs + 1):
        total_loss = 0.0
        for users, pos_items, neg_items in loader:
            users, pos_items, neg_items = users.to(device), pos_items.to(device), neg_items.to(device)
            pos_scores = model(users, pos_items)
            neg_scores = model(users, neg_items)
            loss = -torch.log(torch.sigmoid(pos_scores - neg_scores) + 1e-8).mean()
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            total_loss += loss.item() * len(users)
        scheduler.step()
        if epoch % 5 == 0 or epoch == 1:
            print(f"  Epoch {epoch:3d}/{n_epochs} | BPR Loss: {total_loss/len(dataset):.5f} | LR: {scheduler.get_last_lr()[0]:.2e}")

    return model


# ────────────────────────────────────────────────────────────────────────────
# MODEL: ItemKNN  (Item-based nearest-neighbour CF)
# ────────────────────────────────────────────────────────────────────────────

class ItemKNN:
    """
    Item-based K-Nearest Neighbour Collaborative Filtering.

    Similarity metric: adjusted cosine similarity on the binary user-item matrix.
    Score(u, i) = sum_{j in history(u)} sim(i, j)   — "how similar is i to what u liked"

    Why include it:
      - Classic strong CF baseline, widely used as reference in RecSys papers
      - No training, closed-form — very fast
      - Shows the gain of learned representations (GMF/NeuMF) over hand-crafted similarity
    """
    def __init__(self, k: int = 50):
        self.k = k
        self.sim = None         # (n_items × n_items) top-k sparse similarity
        self.user_history = {}  # stored at fit time for score_candidates

    def fit(self, train_df: pd.DataFrame, n_users: int, n_items: int,
            user_pos: dict) -> 'ItemKNN':
        self.user_history = {u: list(items) for u, items in user_pos.items()}

        # Build binary user-item matrix R  (n_users × n_items)
        R = np.zeros((n_users, n_items), dtype=np.float32)
        for _, row in train_df.iterrows():
            R[int(row['user']), int(row['item'])] = 1.0

        # Column-normalise for cosine similarity
        norms = np.linalg.norm(R, axis=0, keepdims=True)   # (1, n_items)
        norms[norms == 0] = 1.0
        R_norm = R / norms                                   # (n_users, n_items)

        # Item-item cosine: (n_items, n_items)
        print(f"  Computing {n_items}×{n_items} item-item similarity matrix...")
        sim = R_norm.T @ R_norm                              # (n_items, n_items)
        np.fill_diagonal(sim, 0.0)                          # no self-similarity

        # Keep only top-k neighbours per item (zero out the rest)
        if self.k < n_items - 1:
            for i in range(n_items):
                row = sim[i]
                threshold = np.partition(row, -self.k)[-self.k]
                sim[i][row < threshold] = 0.0

        self.sim = sim
        print(f"  ItemKNN fitted. k={self.k}, sim_matrix shape: {sim.shape}")
        return self

    def score_candidates(self, user: int, candidates: list) -> np.ndarray:
        """Score candidates by summing similarity to user's liked items."""
        hist = self.user_history.get(user, [])
        if not hist or self.sim is None:
            return np.zeros(len(candidates), dtype=float)
        hist_arr = np.array(hist, dtype=int)
        cand_arr = np.array(candidates, dtype=int)
        # sim[cand, hist] summed over hist axis
        return self.sim[cand_arr][:, hist_arr].sum(axis=1)

"""## 4. LLM Reranker (NeuMF + LLM)"""

# ── Genre-Based Local Reranker (no API key required) ─────────────────────────
#
# HOW IT WORKS (when no Anthropic API key is set):
#   Step 1 — NeuMF scores all 100 candidates.
#   Step 2 — Top-20 by NeuMF score are selected.
#   Step 3 — A user genre profile is computed from their training history:
#             genre_profile = mean of genre vectors of liked items (L2-normalised)
#   Step 4 — Each top-20 item's genre vector is cosine-sim'd against the profile.
#   Step 5 — Blended score = 0.7 × NeuMF_score + 0.3 × genre_cosine_sim
#   Step 6 — Top-20 re-ordered by blended score; remainder kept by NeuMF order.
#
# This is a lightweight local semantic re-ranker that uses item content features
# to refine collaborative filtering results — the same goal as an LLM reranker,
# without requiring an API key.


def build_genre_matrix(items_df: 'pd.DataFrame', item2idx: dict) -> np.ndarray:
    """
    Build an (n_items × 19) L2-normalised genre feature matrix.
    Row i = genre vector for internal item index i.
    """
    genre_cols = [
        'action', 'adventure', 'animation', 'childrens', 'comedy', 'crime',
        'documentary', 'drama', 'fantasy', 'film_noir', 'horror', 'musical',
        'mystery', 'romance', 'sci_fi', 'thriller', 'war', 'western', 'unknown'
    ]
    n = len(item2idx)
    mat = np.zeros((n, len(genre_cols)), dtype=np.float32)
    for _, row in items_df.iterrows():
        orig_id = row['item_id']
        if orig_id in item2idx:
            idx = item2idx[orig_id]
            mat[idx] = [float(row.get(g, 0)) for g in genre_cols]
    norms = np.linalg.norm(mat, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return mat / norms


@torch.no_grad()
def evaluate_with_genre_reranking(
    neuMF_model:  nn.Module,
    test_df:      'pd.DataFrame',
    eval_negs:    dict,
    user_history: dict,
    genre_mat:    np.ndarray,
    Ks:           tuple = (5, 10),
    n_rerank:     int   = 20,
    alpha:        float = 0.30,   # genre weight (0 = pure NeuMF, 1 = pure genre)
    device:       'torch.device' = None,
) -> dict:
    """
    NeuMF + genre-based local re-ranking.
    Directly affects ranking metrics — visible in the results table.
    """
    if device is None:
        device = next(neuMF_model.parameters()).device
    neuMF_model.eval()
    results = {f'NDCG@{k}': [] for k in Ks}
    results.update({f'HR@{k}': [] for k in Ks})

    for _, row in test_df.iterrows():
        u, pos_item = int(row['user']), int(row['item'])
        candidates  = [pos_item] + eval_negs[u]          # 100 items

        u_t    = torch.tensor([u] * 100, dtype=torch.long, device=device)
        i_t    = torch.tensor(candidates, dtype=torch.long, device=device)
        scores = torch.sigmoid(neuMF_model(u_t, i_t)).cpu().numpy()  # (100,)

        nmf_order  = np.argsort(scores)[::-1].tolist()   # positions in candidates
        top_idx    = nmf_order[:n_rerank]                 # top-20 positions
        rest_idx   = nmf_order[n_rerank:]                 # positions 21-100

        # Build user genre profile from liked training items
        hist = user_history[u]
        if hist:
            profile = genre_mat[hist].mean(axis=0)
            pnorm   = np.linalg.norm(profile)
            if pnorm > 0:
                profile /= pnorm
            top_item_indices   = [candidates[ci] for ci in top_idx]
            genre_sims         = genre_mat[top_item_indices] @ profile   # (n_rerank,)
            top_neuMF_scores   = scores[top_idx]                          # (n_rerank,)
            blended            = (1 - alpha) * top_neuMF_scores + alpha * genre_sims
            reranked           = [top_idx[i] for i in np.argsort(blended)[::-1]]
        else:
            reranked = top_idx   # no history → keep NeuMF order

        final_order = reranked + rest_idx
        pos_rank    = final_order.index(0) + 1   # 1-indexed rank of positive

        for k in Ks:
            results[f'HR@{k}'].append(1 if pos_rank <= k else 0)
            results[f'NDCG@{k}'].append(
                1.0 / np.log2(pos_rank + 1) if pos_rank <= k else 0.0
            )

    return {key: float(np.mean(vals)) for key, vals in results.items()}

# ── Cell 9: LLM Reranker ──────────────────────────────────────────────────────
#
# HOW THE LLM IS INTEGRATED:
#
#  Step 1 — NeuMF scores all 100 candidates (1 pos + 99 neg) per user.
#  Step 2 — Top-20 by NeuMF score are sent to Claude Haiku.
#           Prompt includes the user's last-5 liked movie titles as context.
#  Step 3 — Claude returns those 20 movies re-ordered by predicted relevance.
#  Step 4 — Final ranked list: Claude's order for top-20, NeuMF order for 21-100.
#  Step 5 — Compute NDCG@K and HR@K on the final list.
#
# WHY THIS APPROACH:
#   - Directly and visibly changes ranking outcomes (unlike embedding warm-start)
#   - Bounded API cost: exactly 1 call per test user
#   - LLM leverages semantic movie knowledge that collaborative filtering misses
#     (e.g. genre, tone, themes, era) to improve precision in the top-K band
#
# FALLBACK:
#   Without an API key the function returns identical results to NeuMF alone.

@torch.no_grad()
def evaluate_with_llm_reranking(
    neuMF_model:  nn.Module,
    test_df:      pd.DataFrame,
    eval_negs:    dict,
    user_history: dict,
    idx2item:     dict,
    item_titles:  dict,
    Ks:           tuple = (5, 10),
    n_rerank:     int   = 20,
    api_key:      str   = None,
    device:       torch.device = DEVICE,
    max_users:    int   = None      # set e.g. 100 to limit API spend during tests
) -> dict:

    key     = api_key or os.environ.get('ANTHROPIC_API_KEY')
    use_llm = False
    client  = None

    if key:
        try:
            import anthropic
            client  = anthropic.Anthropic(api_key=key)
            use_llm = True
            print(f"[LLM] Claude Haiku will rerank top-{n_rerank} candidates per user.")
        except ImportError:
            print("[LLM] 'anthropic' not installed. Run: pip install anthropic")
    else:
        print("[LLM] No API key found. Set ANTHROPIC_API_KEY to enable LLM reranking.")
        print("      Falling back to NeuMF scores (results = NeuMF).")

    neuMF_model.eval()
    results = {f'NDCG@{k}': [] for k in Ks}
    results.update({f'HR@{k}': [] for k in Ks})

    n_llm_success, n_llm_fail = 0, 0

    for eval_idx, (_, row) in enumerate(test_df.iterrows()):
        if max_users is not None and eval_idx >= max_users:
            break

        u, pos_item = int(row['user']), int(row['item'])
        candidates  = [pos_item] + eval_negs[u]     # 100 items; pos at slot 0

        u_t    = torch.tensor([u] * 100,  dtype=torch.long, device=device)
        i_t    = torch.tensor(candidates, dtype=torch.long, device=device)
        scores = torch.sigmoid(neuMF_model(u_t, i_t)).cpu().numpy()

        nmf_order = np.argsort(scores)[::-1].tolist()

        if use_llm:
            top_cand_idx  = nmf_order[:n_rerank]          # positions in candidates[]
            rest_cand_idx = nmf_order[n_rerank:]           # positions in candidates[]

            top_item_ids  = [candidates[ci] for ci in top_cand_idx]  # actual item indices

            history_titles = [
                item_titles.get(idx2item.get(it, -1), 'Unknown')
                for it in user_history[u][-5:]
            ]

            cand_info = [
                f"item_id={item_id}: {item_titles.get(idx2item.get(item_id, -1), 'Unknown')}"
                for item_id in top_item_ids
            ]

            prompt = (
                f"A user recently enjoyed: {', '.join(history_titles)}.\n\n"
                f"Rank the following {n_rerank} movies from MOST to LEAST relevant "
                f"for this user based on their taste.\n"
                f"Output ONLY a valid JSON array of item_ids in ranked order. "
                f"Example: [42, 7, 15, ...]  — no explanation, no markdown.\n\n"
                "Candidates:\n" + "\n".join(cand_info)
            )

            llm_reranked = top_cand_idx  # default: keep NeuMF order
            try:
                resp     = client.messages.create(
                    model      = 'claude-haiku-4-5-20251001',
                    max_tokens = 256,
                    messages   = [{'role': 'user', 'content': prompt}]
                )
                raw_text = resp.content[0].text.strip()

                s, e = raw_text.find('['), raw_text.rfind(']') + 1
                if s != -1 and e > s:
                    ranked_ids = json.loads(raw_text[s:e])  # LLM's item_id order

                    item_id_to_cand_pos = {candidates[ci]: ci for ci in top_cand_idx}
                    llm_reranked = [
                        item_id_to_cand_pos[rid]
                        for rid in ranked_ids
                        if rid in item_id_to_cand_pos
                    ]
                    seen = set(llm_reranked)
                    for ci in top_cand_idx:
                        if ci not in seen:
                            llm_reranked.append(ci)

                n_llm_success += 1

            except Exception as e:
                n_llm_fail += 1
            final_order = llm_reranked + rest_cand_idx

        else:
            final_order = nmf_order   # no LLM: same as NeuMF

        pos_rank = final_order.index(0) + 1   # 1-indexed rank

        for k in Ks:
            results[f'HR@{k}'].append(1 if pos_rank <= k else 0)
            results[f'NDCG@{k}'].append(
                1.0 / np.log2(pos_rank + 1) if pos_rank <= k else 0.0
            )

    if use_llm:
        n_total = n_llm_success + n_llm_fail
        print(f"[LLM] Calls: {n_llm_success}/{n_total} succeeded, {n_llm_fail} fell back to NeuMF.")

    return {key: float(np.mean(vals)) for key, vals in results.items()}

"""## 5. Train & Evaluate All Models"""

# ── Cell 10: Hyperparameters ──────────────────────────────────────────────────
#
# Selected via informal grid search on a 10% validation holdout:
#   emb_dim      ∈ {32, 64}        → 64 won
#   mlp_dims     ∈ multiple configs → (256,128,64) won
#   lr           ∈ {5e-4, 1e-3}    → 1e-3 won
#   neg_ratio    ∈ {2, 4}          → 4 won

HP = dict(
    emb_dim      = 64,
    mlp_dims     = (256, 128, 64),
    dropout      = 0.2,
    n_epochs     = 50,   # ↑ from 30 — CosineAnnealingLR benefits from more epochs
    batch_size   = 2048,
    lr           = 1e-3,
    weight_decay = 1e-5,
    neg_ratio    = 4,
)

# ── API key for NeuMF + LLM model ────────────────────────────────────────────
# Option 1: environment variable (recommended)
#   export ANTHROPIC_API_KEY="sk-ant-..."
# Option 2: hardcode below (for quick testing only)
API_KEY = os.environ.get('ANTHROPIC_API_KEY', None)
# API_KEY = 'sk-ant-...'   # uncomment and paste your key here if needed

print(f"LLM reranking: {'ENABLED' if API_KEY else 'DISABLED (no API key)'}")
print(f"Hyperparameters: {HP}")

# ── Model 1/5 — Popularity Baseline ──────────────────────────────────────────
print("=" * 60)
print("MODEL 1/5 — Popularity Baseline")
print("=" * 60)
pop_model = PopularityModel().fit(train_df)
res_pop   = evaluate_ranking(pop_model, test_df, EVAL_NEGS, is_neural=False)
print(f"  NDCG@5={res_pop['NDCG@5']:.4f}  NDCG@10={res_pop['NDCG@10']:.4f}  "
      f"NDCG@15={res_pop['NDCG@15']:.4f}  NDCG@20={res_pop['NDCG@20']:.4f}  "
      f"HR@5={res_pop['HR@5']:.4f}  HR@10={res_pop['HR@10']:.4f}  "
      f"HR@15={res_pop['HR@15']:.4f}  HR@20={res_pop['HR@20']:.4f}")

# ── Model 2/5 — MF (GMF) ─────────────────────────────────────────────────────
print("=" * 60)
print("MODEL 2/5 — MF (GMF — Generalised Matrix Factorisation)")
print("=" * 60)
torch.manual_seed(SEED)
gmf_model = GMF(n_users, n_items, emb_dim=HP['emb_dim']).to(DEVICE)
print(f"  Parameters: {sum(p.numel() for p in gmf_model.parameters()):,}")
gmf_model = train_model(
    gmf_model, train_df, user_pos, n_items,
    n_epochs=HP['n_epochs'], batch_size=HP['batch_size'],
    lr=HP['lr'], weight_decay=HP['weight_decay'],
    neg_ratio=HP['neg_ratio'], device=DEVICE
)

res_gmf = evaluate_ranking(gmf_model, test_df, EVAL_NEGS)
print(f"  NDCG@5={res_gmf['NDCG@5']:.4f}  NDCG@10={res_gmf['NDCG@10']:.4f}  "
      f"NDCG@15={res_gmf['NDCG@15']:.4f}  NDCG@20={res_gmf['NDCG@20']:.4f}  "
      f"HR@5={res_gmf['HR@5']:.4f}  HR@10={res_gmf['HR@10']:.4f}  "
      f"HR@15={res_gmf['HR@15']:.4f}  HR@20={res_gmf['HR@20']:.4f}")

# ── Model 3/5 — Pure MLP ─────────────────────────────────────────────────────
# (Also serves as the pre-training component for NeuMF-pretrained)
print("=" * 60)
print("MODEL 3/5 — Pure MLP (also used for NeuMF pre-training)")
print("=" * 60)
torch.manual_seed(SEED)
mlp_pretrain = MLPModel(
    n_users, n_items,
    emb_dim  = HP['emb_dim'],
    mlp_dims = HP['mlp_dims'],
    dropout  = HP['dropout']
).to(DEVICE)
print(f"  Parameters: {sum(p.numel() for p in mlp_pretrain.parameters()):,}")
mlp_pretrain = train_model(
    mlp_pretrain, train_df, user_pos, n_items,
    n_epochs=HP['n_epochs'], batch_size=HP['batch_size'],
    lr=HP['lr'], weight_decay=HP['weight_decay'],
    neg_ratio=HP['neg_ratio'], device=DEVICE
)

res_mlp = evaluate_ranking(mlp_pretrain, test_df, EVAL_NEGS)
print(f"  NDCG@5={res_mlp['NDCG@5']:.4f}  NDCG@10={res_mlp['NDCG@10']:.4f}  "
      f"NDCG@15={res_mlp['NDCG@15']:.4f}  NDCG@20={res_mlp['NDCG@20']:.4f}  "
      f"HR@5={res_mlp['HR@5']:.4f}  HR@10={res_mlp['HR@10']:.4f}  "
      f"HR@15={res_mlp['HR@15']:.4f}  HR@20={res_mlp['HR@20']:.4f}")

# ── Model 4/5 — NeuMF ────────────────────────────────────────────────────────
print("=" * 60)
print("MODEL 4/5 — NeuMF (GMF + MLP, random init)")
print("=" * 60)
torch.manual_seed(SEED)
neuMF_model = NeuMF(
    n_users, n_items,
    emb_dim  = HP['emb_dim'],
    mlp_dims = HP['mlp_dims'],
    dropout  = HP['dropout']
).to(DEVICE)
print(f"  Parameters: {sum(p.numel() for p in neuMF_model.parameters()):,}")
neuMF_model = train_model(
    neuMF_model, train_df, user_pos, n_items,
    n_epochs=HP['n_epochs'], batch_size=HP['batch_size'],
    lr=HP['lr'], weight_decay=HP['weight_decay'],
    neg_ratio=HP['neg_ratio'], device=DEVICE
)

res_neuMF = evaluate_ranking(neuMF_model, test_df, EVAL_NEGS)
print(f"  NDCG@5={res_neuMF['NDCG@5']:.4f}  NDCG@10={res_neuMF['NDCG@10']:.4f}  "
      f"NDCG@15={res_neuMF['NDCG@15']:.4f}  NDCG@20={res_neuMF['NDCG@20']:.4f}  "
      f"HR@5={res_neuMF['HR@5']:.4f}  HR@10={res_neuMF['HR@10']:.4f}  "
      f"HR@15={res_neuMF['HR@15']:.4f}  HR@20={res_neuMF['HR@20']:.4f}")

# ── Model 5/5 — NeuMF + Pre-trained Init ─────────────────────────────────────
print("=" * 60)
print("MODEL 5/5 — NeuMF + Pre-trained Init (from GMF + MLP)")
print("=" * 60)
print("  Technique: He et al. NeuMF paper §3.4")
print("  Init GMF branch from trained GMF, MLP branch from trained MLP,")
print("  then fine-tune end-to-end with a lower LR for stable convergence.")
torch.manual_seed(SEED)
neuMF_pt = NeuMF(
    n_users, n_items,
    emb_dim  = HP['emb_dim'],
    mlp_dims = HP['mlp_dims'],
    dropout  = HP['dropout']
).to(DEVICE)
neuMF_pt = init_neumf_from_pretrained(neuMF_pt, gmf_model, mlp_pretrain)
print(f"  Parameters: {sum(p.numel() for p in neuMF_pt.parameters()):,}")
# Fine-tune with slightly lower LR (weights already well initialised)
neuMF_pt = train_model(
    neuMF_pt, train_df, user_pos, n_items,
    n_epochs=HP['n_epochs'], batch_size=HP['batch_size'],
    lr=HP['lr'] * 0.5,          # half LR for stable fine-tuning
    weight_decay=HP['weight_decay'],
    neg_ratio=HP['neg_ratio'], device=DEVICE
)

res_neuMF_pt = evaluate_ranking(neuMF_pt, test_df, EVAL_NEGS)
print(f"  NDCG@5={res_neuMF_pt['NDCG@5']:.4f}  NDCG@10={res_neuMF_pt['NDCG@10']:.4f}  "
      f"NDCG@15={res_neuMF_pt['NDCG@15']:.4f}  NDCG@20={res_neuMF_pt['NDCG@20']:.4f}  "
      f"HR@5={res_neuMF_pt['HR@5']:.4f}  HR@10={res_neuMF_pt['HR@10']:.4f}  "
      f"HR@15={res_neuMF_pt['HR@15']:.4f}  HR@20={res_neuMF_pt['HR@20']:.4f}")

# ── Model 6: BPR-MF (GMF with BPR pairwise loss) ─────────────────────────────
print("=" * 60)
print("MODEL 6 — BPR-MF (GMF architecture, BPR pairwise loss)")
print("=" * 60)
print("  BPR loss: L = -E[log sigmoid(score_pos - score_neg)]")
print("  Directly optimises ranking order (vs. pointwise BCE in other models).")
torch.manual_seed(SEED)
bpr_gmf = GMF(n_users, n_items, emb_dim=HP['emb_dim']).to(DEVICE)
print(f"  Parameters: {sum(p.numel() for p in bpr_gmf.parameters()):,}")
bpr_gmf = train_bpr(
    bpr_gmf, train_df, user_pos, n_items,
    n_epochs    = HP['n_epochs'],
    batch_size  = HP['batch_size'],
    lr          = HP['lr'],
    weight_decay= HP['weight_decay'],
    device      = DEVICE,
)
res_bpr = evaluate_ranking(bpr_gmf, test_df, EVAL_NEGS)
print(f"  NDCG@5={res_bpr['NDCG@5']:.4f}  NDCG@10={res_bpr['NDCG@10']:.4f}  "
      f"NDCG@15={res_bpr['NDCG@15']:.4f}  NDCG@20={res_bpr['NDCG@20']:.4f}  "
      f"HR@5={res_bpr['HR@5']:.4f}  HR@10={res_bpr['HR@10']:.4f}  "
      f"HR@15={res_bpr['HR@15']:.4f}  HR@20={res_bpr['HR@20']:.4f}")

# ── Model 7: ItemKNN ─────────────────────────────────────────────────────────
print("=" * 60)
print("MODEL 7 — ItemKNN (item-based nearest-neighbour CF)")
print("=" * 60)
print("  Classic CF baseline: scores candidates by similarity to user history.")
item_knn = ItemKNN(k=50).fit(train_df, n_users, n_items, user_pos)
res_knn  = evaluate_ranking(item_knn, test_df, EVAL_NEGS, is_neural=False)
print(f"  NDCG@5={res_knn['NDCG@5']:.4f}  NDCG@10={res_knn['NDCG@10']:.4f}  "
      f"NDCG@15={res_knn['NDCG@15']:.4f}  NDCG@20={res_knn['NDCG@20']:.4f}  "
      f"HR@5={res_knn['HR@5']:.4f}  HR@10={res_knn['HR@10']:.4f}  "
      f"HR@15={res_knn['HR@15']:.4f}  HR@20={res_knn['HR@20']:.4f}")

# ── Genre Reranker Setup + Eval ──────────────────────────────────────────────
# Build genre matrix (done once)
genre_mat = build_genre_matrix(items_df, item2idx)
print(f"Genre matrix shape: {genre_mat.shape}  (n_items × 19 genres, L2-normalised)")

# Evaluate NeuMF-pretrained + genre reranker (no API key required)
print("\n" + "=" * 60)
print("RERANKER: NeuMF-pretrained + Genre Reranker (local, no API key)")
print("=" * 60)
res_genre_rr = evaluate_with_genre_reranking(
    neuMF_model  = neuMF_pt,   # best NeuMF (pre-trained init)
    test_df      = test_df,
    eval_negs    = EVAL_NEGS,
    user_history = user_history,
    genre_mat    = genre_mat,
    Ks           = (5, 10, 15, 20),
    n_rerank     = 20,
    alpha        = 0.30,       # 30% genre, 70% NeuMF
    device       = DEVICE,
)
print(f"  NDCG@5={res_genre_rr['NDCG@5']:.4f}  NDCG@10={res_genre_rr['NDCG@10']:.4f}  "
      f"NDCG@15={res_genre_rr['NDCG@15']:.4f}  NDCG@20={res_genre_rr['NDCG@20']:.4f}  "
      f"HR@5={res_genre_rr['HR@5']:.4f}  HR@10={res_genre_rr['HR@10']:.4f}  "
      f"HR@15={res_genre_rr['HR@15']:.4f}  HR@20={res_genre_rr['HR@20']:.4f}")

# Also try original LLM reranker if API key is available (optional)
print("\n" + "=" * 60)
print("RERANKER: NeuMF + LLM Reranker (requires ANTHROPIC_API_KEY)")
print("=" * 60)
res_llm = evaluate_with_llm_reranking(
    neuMF_model  = neuMF_model,
    test_df      = test_df,
    eval_negs    = EVAL_NEGS,
    user_history = user_history,
    idx2item     = idx2item,
    item_titles  = item_titles,
    Ks           = (5, 10, 15, 20),
    n_rerank     = 20,
    api_key      = API_KEY,
    device       = DEVICE,
    max_users    = None
)
print(f"  NDCG@5={res_llm['NDCG@5']:.4f}  NDCG@10={res_llm['NDCG@10']:.4f}  "
      f"NDCG@15={res_llm['NDCG@15']:.4f}  NDCG@20={res_llm['NDCG@20']:.4f}  "
      f"HR@5={res_llm['HR@5']:.4f}  HR@10={res_llm['HR@10']:.4f}  "
      f"HR@15={res_llm['HR@15']:.4f}  HR@20={res_llm['HR@20']:.4f}")

# ── Comparison Study — 5 configs (20 epochs each for speed) ──────────────────
# Compares: GMF, MLP, NeuMF, BPR-MF (NeuMF+BPR loss), NeuMF-wide
# Supplements the full 50-epoch main models above with architecture/loss variants.

SIMPLE_EPOCHS = 20

simple_cfgs = [
    ("GMF",          "GMF",   dict(emb_dim=64)),
    ("MLP",          "MLP",   dict(emb_dim=64, mlp_dims=(128, 64, 32), dropout=0.2)),
    ("NeuMF",        "NeuMF", dict(emb_dim=64, mlp_dims=(128, 64, 32), dropout=0.2)),
    ("NeuMF-wide",   "NeuMF", dict(emb_dim=128, mlp_dims=(512, 256, 128), dropout=0.2)),
    ("BPR-NeuMF",    "BPR-NeuMF", dict(emb_dim=64, mlp_dims=(128, 64, 32), dropout=0.2)),
]

simple_results = {}

for label, cls_name, kwargs in simple_cfgs:
    print(f"\n── {label} ─────────────────────────────────")
    torch.manual_seed(SEED)

    if cls_name == "GMF":
        m = GMF(n_users, n_items, **kwargs).to(DEVICE)
        m = train_model(m, train_df, user_pos, n_items,
                        n_epochs=SIMPLE_EPOCHS, batch_size=HP['batch_size'],
                        lr=HP['lr'], weight_decay=HP['weight_decay'],
                        neg_ratio=HP['neg_ratio'], device=DEVICE)
    elif cls_name == "MLP":
        m = MLPModel(n_users, n_items, **kwargs).to(DEVICE)
        m = train_model(m, train_df, user_pos, n_items,
                        n_epochs=SIMPLE_EPOCHS, batch_size=HP['batch_size'],
                        lr=HP['lr'], weight_decay=HP['weight_decay'],
                        neg_ratio=HP['neg_ratio'], device=DEVICE)
    elif cls_name == "NeuMF":
        kw = {k: v for k, v in kwargs.items() if k != 'bpr'}
        m = NeuMF(n_users, n_items, **kw).to(DEVICE)
        m = train_model(m, train_df, user_pos, n_items,
                        n_epochs=SIMPLE_EPOCHS, batch_size=HP['batch_size'],
                        lr=HP['lr'], weight_decay=HP['weight_decay'],
                        neg_ratio=HP['neg_ratio'], device=DEVICE)
    elif cls_name == "BPR-NeuMF":
        # NeuMF architecture but trained with BPR pairwise loss
        m = NeuMF(n_users, n_items, **kwargs).to(DEVICE)
        m = train_bpr(m, train_df, user_pos, n_items,
                      n_epochs=SIMPLE_EPOCHS, batch_size=HP['batch_size'],
                      lr=HP['lr'], weight_decay=HP['weight_decay'],
                      device=DEVICE)

    r = evaluate_ranking(m, test_df, EVAL_NEGS)
    simple_results[label] = r
    print(f"  NDCG@5={r['NDCG@5']:.4f}  NDCG@10={r['NDCG@10']:.4f}  "
          f"NDCG@15={r['NDCG@15']:.4f}  NDCG@20={r['NDCG@20']:.4f}  "
          f"HR@5={r['HR@5']:.4f}  HR@10={r['HR@10']:.4f}  "
          f"HR@15={r['HR@15']:.4f}  HR@20={r['HR@20']:.4f}")
    del m  # free memory

print("\n✔ Comparison study complete.")

"""## 6. Final Comparison Table"""

# ══════════════════════════════════════════════════════════════════════════════
# COMPREHENSIVE RESULTS — MovieLens 100K  (K = 5, 10, 15, 20)
# ══════════════════════════════════════════════════════════════════════════════

KS = [5, 10, 15, 20]

# ── Section A: All main models (fully trained) ───────────────────────────────
main_results = {
    'Popularity'              : res_pop,
    'ItemKNN'                 : res_knn,
    'MF / GMF'                : res_gmf,
    'BPR-MF'                  : res_bpr,
    'Pure MLP'                : res_mlp,
    'NeuMF (random init)'     : res_neuMF,
    'NeuMF + Pretrained Init' : res_neuMF_pt,
    'NeuMF + Genre Reranker'  : res_genre_rr,
    'NeuMF + LLM Reranker'    : res_llm,
}

# ── Metric column order ───────────────────────────────────────────────────────
ndcg_cols = [f'NDCG@{k}' for k in KS]
hr_cols   = [f'HR@{k}'   for k in KS]
all_cols  = ndcg_cols + hr_cols

# ── Column widths ────────────────────────────────────────────────────────────
NAME_W = 28
COL_W  = 9

# Helper: one table row
def row(name, m, cols):
    cells = ''.join(f"{m[c]:>{COL_W}.4f}" for c in cols)
    return f"  {name:<{NAME_W}}{cells}"

# ── Header ────────────────────────────────────────────────────────────────────
header_cols = ''.join(f"{c:>{COL_W}}" for c in all_cols)
sep = '─' * (NAME_W + 2 + COL_W * len(all_cols))

def print_table(title, subtitle, results_dict):
    W = len(sep)
    print()
    print('╔' + '═'*W + '╗')
    print('║' + title.center(W) + '║')
    print('║' + subtitle.center(W) + '║')
    print('╠' + '═'*W + '╣')
    print(f"  {'Model':<{NAME_W}}" + header_cols)
    print('  ' + sep)
    for name, m in results_dict.items():
        print(row(name, m, all_cols))
    print('╚' + '═'*W + '╝')

# ── TABLE 1: Main models ──────────────────────────────────────────────────────
print_table(
    "  FINAL RESULTS — MovieLens 100K (Implicit Feedback)",
    "  Protocol: Leave-one-out · 99 fixed negatives/user · All 7 main models",
    main_results
)

# ── TABLE 2: Comparison study ─────────────────────────────────────────────────
print_table(
    "  COMPARISON STUDY — Architecture & Loss Function Ablation (20 epochs)",
    "  5 configurations: GMF, MLP, NeuMF, NeuMF-wide, BPR-NeuMF",
    simple_results
)

# ── Pandas summary sorted by NDCG@10 ─────────────────────────────────────────
all_res = {**main_results, **simple_results}
summary = pd.DataFrame(all_res).T[all_cols]
summary.index.name = 'Model'
print()
print("All results sorted by NDCG@10:")
print(summary.round(4).sort_values('NDCG@10', ascending=False).to_string())

# ── Relative improvement vs. Popularity ───────────────────────────────────────
print()
print("Relative improvement vs. Popularity (NDCG@10):")
base = res_pop['NDCG@10']
for name, m in all_res.items():
    delta = (m['NDCG@10'] - base) / base * 100
    arrow = '▲' if delta > 0 else ('▼' if delta < 0 else '—')
    print(f"  {name:<35}: {m['NDCG@10']:.4f}  {arrow} {abs(delta):+.1f}%")

@torch.no_grad()
def top_k_for_user(
    model:    nn.Module,
    u:        int,
    user_pos: dict,
    n_items:  int,
    idx2item: dict,
    titles:   dict,
    k:        int = 10,
    device:   torch.device = DEVICE
) -> pd.DataFrame:
    """Return a DataFrame of top-K recommended items for a user."""

    model.eval()

    unseen = [i for i in range(n_items) if i not in user_pos[u]]

    chunk  = 4096
    scores = []

    for s in range(0, len(unseen), chunk):
        u_t = torch.tensor([u] * len(unseen[s:s+chunk]), dtype=torch.long, device=device)
        i_t = torch.tensor(unseen[s:s+chunk], dtype=torch.long, device=device)
        scores.append(torch.sigmoid(model(u_t, i_t)).cpu())

    scores = torch.cat(scores).numpy()

    top_idx = np.argsort(scores)[::-1][:k]

    rows = []
    for rank, ci in enumerate(top_idx, 1):
        item_new  = unseen[ci]
        item_orig = idx2item.get(item_new, -1)

        rows.append({
            'Rank': rank,
            'item_idx': item_new,
            'Title': titles.get(item_orig, 'Unknown'),
            'Score': round(float(scores[ci]), 4)
        })

    return pd.DataFrame(rows)





demo_user = 0

for K in [5, 10, 15, 20]:
    print(f"\nTop-{K} NeuMF recommendations for user {demo_user}:")
    recs = top_k_for_user(
        neuMF_model, demo_user,
        user_pos, n_items,
        idx2item, item_titles,
        k=K
    )
    print(recs.to_string(index=False))